# config about player shell
player-shell:
  enable: true
  prefix: '@'

# tick rate, run ankh-tick in x ticks
tick-rate: 3

item:
  lore-fetcher:
    mark-start: '@ankh-item '
    mark-end: '@'

performance:
  cache-concurrency-level: -1
  cache-initial-capacity: -1
  cache-key-weak: true
  cache-value-weak: false

# select service
service:
  # hologram service, empty to auto-detect
  # 'holographic-displays': https://github.com/filoghost/HolographicDisplays
  # 'nop': no operation
  hologram: ''
  # Support values: 'bsh' ...(add by other plugin)
  # 'groovy' if enable service-groovy
  # 'js' 'nashorn' if enable service-js-nashorn
  # 'kether' if enable service-kether
  script: 'bsh'
  # Support values: 'pdc' 'filesystem' ...(add by other plugin)
  world-storage: 'pdc'
  # Support values: 'pdc' 'nbt' ...(add by other plugin)
  item-tagger: 'pdc'