name: ankh-core
version: 1.0-SNAPSHOT
main: org.inksnow.ankh.loader.AnkhCoreLoaderPlugin
load: STARTUP
authors:
  - InkerBot
softdepend: [ HolographicDisplays ]

ankh-self-as-api: true
ankh-classpath:
  "kotlin.": SELF_ONLY
  "bsh.": SELF_ONLY
  "org.apache.logging.": SELF_ONLY
  "io.github.bakedlibs.": SELF_ONLY
  "com.google.inject.": SELF_ONLY
  "org.objectweb.asm.": SELF_ONLY
  "org.yaml.snakeyaml.": SELF_ONLY
  "com.typesafe.config.": SELF_ONLY
  "com.google.gson.": SELF_ONLY